# Generated by Django 2.2.5 on 2019-09-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_posted',
            new_name='date_posted',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
